<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
      DB::table('cities')->truncate();
      DB::table('cities')->insert(['state' =>  1, 'name' => 'Leticia']);
      DB::table('cities')->insert(['state' =>  1, 'name' => 'Puerto Nariño']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Abejorral']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Abriaquí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Alejandria']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Amagá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Amalfi']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Andes']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Angelópolis']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Angostura']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Anorí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Anzá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Apartadó']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Arboletes']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Argelia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Armenia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Barbosa']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Bello']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Belmira']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Betania']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Betulia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Bolívar']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Briceño']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Burítica']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Caicedo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Caldas']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Campamento']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Caracolí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Caramanta']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Carepa']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Carmen de Viboral']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Carolina']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Caucasia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Cañasgordas']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Chigorodó']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Cisneros']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Cocorná']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Concepción']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Concordia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Copacabana']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Cáceres']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Dabeiba']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Don Matías']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Ebéjico']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'El Bagre']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Entrerríos']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Envigado']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Fredonia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Frontino']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Giraldo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Girardota']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Granada']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Guadalupe']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Guarne']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Guatapé']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Gómez Plata']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Heliconia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Hispania']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Itagüí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Ituango']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Jardín']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Jericó']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'La Ceja']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'La Estrella']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'La Pintada']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'La Unión']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Liborina']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Maceo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Marinilla']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Medellín']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Montebello']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Murindó']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Mutatá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Nariño']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Nechí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Necoclí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Olaya']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Peque']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Peñol']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Pueblorrico']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Puerto Berrío']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Puerto Nare']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Puerto Triunfo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Remedios']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Retiro']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Ríonegro']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Sabanalarga']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Sabaneta']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Salgar']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Andrés de Cuerquía']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Carlos']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Francisco']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Jerónimo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San José de Montaña']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Juan de Urabá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Luís']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Pedro']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Pedro de Urabá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Rafael']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Roque']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'San Vicente']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Santa Bárbara']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Santa Fé de Antioquia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Santa Rosa de Osos']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Santo Domingo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Santuario']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Segovia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Sonsón']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Sopetrán']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Tarazá']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Tarso']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Titiribí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Toledo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Turbo']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Támesis']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Uramita']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Urrao']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Valdivia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Valparaiso']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Vegachí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Venecia']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Vigía del Fuerte']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Yalí']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Yarumal']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Yolombó']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Yondó (Casabe)']);
      DB::table('cities')->insert(['state' =>  2, 'name' => 'Zaragoza']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Arauca']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Arauquita']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Cravo Norte']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Fortúl']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Puerto Rondón']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Saravena']);
      DB::table('cities')->insert(['state' =>  3, 'name' => 'Tame']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Baranoa']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Barranquilla']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Campo de la Cruz']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Candelaria']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Galapa']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Juan de Acosta']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Luruaco']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Malambo']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Manatí']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Palmar de Varela']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Piojo']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Polonuevo']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Ponedera']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Puerto Colombia']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Repelón']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Sabanagrande']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Sabanalarga']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Santa Lucía']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Santo Tomás']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Soledad']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Suan']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Tubará']);
      DB::table('cities')->insert(['state' =>  4, 'name' => 'Usiacuri']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Achí']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Altos del Rosario']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Arenal']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Arjona']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Arroyohondo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Barranco de Loba']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Calamar']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Cantagallo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Cartagena']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Cicuco']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Clemencia']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Córdoba']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'El Carmen de Bolívar']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'El Guamo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'El Peñon']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Hatillo de Loba']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Magangué']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Mahates']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Margarita']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'María la Baja']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Mompós']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Montecristo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Morales']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Norosí']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Pinillos']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Regidor']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Río Viejo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Cristobal']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Estanislao']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Fernando']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Jacinto']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Jacinto del Cauca']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Juan de Nepomuceno']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Martín de Loba']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'San Pablo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Santa Catalina']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Santa Rosa ']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Santa Rosa del Sur']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Simití']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Soplaviento']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Talaigua Nuevo']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Tiquisio (Puerto Rico)']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Turbaco']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Turbaná']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Villanueva']);
      DB::table('cities')->insert(['state' =>  5, 'name' => 'Zambrano']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Almeida']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Aquitania']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Arcabuco']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Belén']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Berbeo']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Beteitiva']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Boavita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Boyacá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Briceño']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Buenavista']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Busbanza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Caldas']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Campohermoso']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Cerinza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chinavita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chiquinquirá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chiscas']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chitaraque']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chivatá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chíquiza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Chívor']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Ciénaga']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Coper']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Corrales']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Covarachía']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Cubará']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Cucaita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Cuitiva']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Cómbita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Duitama']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'El Cocuy']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'El Espino']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Firavitoba']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Floresta']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Gachantivá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Garagoa']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Guacamayas']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Guateque']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Guayatá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Guicán']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Gámeza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Izá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Jenesano']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Jericó']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'La Capilla']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'La Uvita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'La Victoria']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Labranzagrande']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Macanal']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Maripí']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Miraflores']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Mongua']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Monguí']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Moniquirá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Motavita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Muzo']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Nobsa']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Nuevo Colón']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Oicatá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Otanche']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Pachavita']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Paipa']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Pajarito']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Panqueba']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Pauna']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Paya']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Paz de Río']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Pesca']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Pisva']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Puerto Boyacá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Páez']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Quipama']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Ramiriquí']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Rondón']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Ráquira']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Saboyá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Samacá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San Eduardo']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San José de Pare']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San Luís de Gaceno']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San Mateo']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San Miguel de Sema']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'San Pablo de Borbur']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Santa María']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Santa Rosa de Viterbo']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Santa Sofía']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Santana']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sativanorte']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sativasur']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Siachoque']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Soatá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Socha']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Socotá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sogamoso']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Somondoco']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sora']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Soracá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sotaquirá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Susacón']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sutamarchán']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sutatenza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Sáchica']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tasco']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tenza']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tibaná']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tibasosa']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tinjacá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tipacoque']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Toca']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Toguí']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Topagá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tota']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tunja']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tunungua']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Turmequé']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tuta']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Tutasá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Ventaquemada']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Villa de Leiva']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Viracachá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Zetaquirá']);
      DB::table('cities')->insert(['state' =>  6, 'name' => 'Úmbita']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Aguadas']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Anserma']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Aranzazu']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Belalcázar']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Chinchiná']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Filadelfia']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'La Dorada']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'La Merced']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'La Victoria']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Manizales']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Manzanares']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Marmato']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Marquetalia']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Marulanda']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Neira']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Norcasia']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Palestina']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Pensilvania']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Pácora']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Risaralda']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Río Sucio']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Salamina']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Samaná']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'San José']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Supía']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Villamaría']);
      DB::table('cities')->insert(['state' =>  7, 'name' => 'Viterbo']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Albania']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Belén de los Andaquíes']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Cartagena del Chairá']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Curillo']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'El Doncello']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'El Paujil']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Florencia']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'La Montañita']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Milán']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Morelia']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Puerto Rico']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'San José del Fragua']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'San Vicente del Caguán']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Solano']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Solita']);
      DB::table('cities')->insert(['state' =>  8, 'name' => 'Valparaiso']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Aguazul']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Chámeza']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Hato Corozal']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'La Salina']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Maní']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Monterrey']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Nunchía']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Orocué']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Paz de Ariporo']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Pore']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Recetor']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Sabanalarga']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'San Luís de Palenque']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Sácama']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Tauramena']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Trinidad']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Támara']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Villanueva']);
      DB::table('cities')->insert(['state' =>  9, 'name' => 'Yopal']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Almaguer']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Argelia']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Balboa']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Bolívar']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Buenos Aires']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Cajibío']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Caldono']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Caloto']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Corinto']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'El Tambo']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Florencia']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Guachené']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Guapí']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Inzá']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Jambaló']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'La Sierra']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'La Vega']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'López (Micay)']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Mercaderes']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Miranda']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Morales']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Padilla']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Patía (El Bordo)']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Piamonte']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Piendamó']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Popayán']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Puerto Tejada']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Puracé (Coconuco)']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Páez (Belalcazar)']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Rosas']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'San Sebastián']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Santa Rosa']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Santander de Quilichao']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Silvia']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Sotara (Paispamba)']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Sucre']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Suárez']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Timbiquí']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Timbío']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Toribío']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Totoró']);
      DB::table('cities')->insert(['state' =>  10, 'name' => 'Villa Rica']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Aguachica']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Agustín Codazzi']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Astrea']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Becerríl']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Bosconia']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Chimichagua']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Chiriguaná']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Curumaní']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'El Copey']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'El Paso']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Gamarra']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Gonzalez']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'La Gloria']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'La Jagua de Ibirico']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'La Paz (Robles)']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Manaure Balcón del Cesar']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Pailitas']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Pelaya']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Pueblo Bello']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Río de oro']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'San Alberto']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'San Diego']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'San Martín']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Tamalameque']);
      DB::table('cities')->insert(['state' =>  11, 'name' => 'Valledupar']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Acandí']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Alto Baudó (Pie de Pato)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Atrato (Yuto)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Bagadó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Bahía Solano (Mútis)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Bajo Baudó (Pizarro)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Belén de Bajirá']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Bojayá (Bellavista)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Cantón de San Pablo']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Carmen del Darién (CURBARADÓ)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Condoto']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Cértegui']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'El Carmen de Atrato']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Istmina']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Juradó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Lloró']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Medio Atrato']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Medio Baudó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Medio San Juan (ANDAGOYA)']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Novita']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Nuquí']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Quibdó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Río Iró']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Río Quito']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Ríosucio']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'San José del Palmar']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Santa Genoveva de Docorodó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Sipí']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Tadó']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Unguía']);
      DB::table('cities')->insert(['state' =>  12, 'name' => 'Unión Panamericana (ÁNIMAS)']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Ayapel']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Buenavista']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Canalete']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Cereté']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Chimá']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Chinú']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Ciénaga de Oro']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Cotorra']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'La Apartada y La Frontera']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Lorica']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Los Córdobas']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Momil']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Montelíbano']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Monteria']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Moñitos']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Planeta Rica']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Pueblo Nuevo']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Puerto Escondido']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Puerto Libertador']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Purísima']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Sahagún']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San Andrés Sotavento']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San Antero']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San Bernardo del Viento']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San Carlos']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San José de Uré']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'San Pelayo']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Tierralta']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Tuchín']);
      DB::table('cities')->insert(['state' =>  13, 'name' => 'Valencia']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Agua de Dios']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Albán']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Anapoima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Anolaima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Apulo']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Arbeláez']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Beltrán']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Bituima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Bogotá D.C.']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Bojacá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cabrera']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cachipay']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cajicá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Caparrapí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Carmen de Carupa']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Chaguaní']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Chipaque']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Choachí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Chocontá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Chía']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cogua']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cota']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cucunubá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Cáqueza']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'El Colegio']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'El Peñón']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'El Rosal']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Facatativá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Fosca']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Funza']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Fusagasugá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Fómeque']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Fúquene']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Gachalá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Gachancipá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Gachetá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Gama']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Girardot']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Granada']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guachetá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guaduas']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guasca']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guataquí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guatavita']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guayabal de Siquima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Guayabetal']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Gutiérrez']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Jerusalén']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Junín']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'La Calera']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'La Mesa']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'La Palma']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'La Peña']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'La Vega']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Lenguazaque']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Machetá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Madrid']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Manta']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Medina']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Mosquera']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Nariño']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Nemocón']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Nilo']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Nimaima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Nocaima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Pacho']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Paime']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Pandi']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Paratebueno']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Pasca']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Puerto Salgar']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Pulí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Quebradanegra']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Quetame']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Quipile']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Ricaurte']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'San Antonio de Tequendama']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'San Bernardo']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'San Cayetano']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'San Francisco']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'San Juan de Río Seco']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Sasaima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Sesquilé']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Sibaté']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Silvania']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Simijaca']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Soacha']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Sopó']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Subachoque']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Suesca']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Supatá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Susa']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Sutatausa']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tabio']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tausa']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tena']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tenjo']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tibacuy']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tibirita']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tocaima']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Tocancipá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Topaipí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Ubalá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Ubaque']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Ubaté']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Une']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Venecia (Ospina Pérez)']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Vergara']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Viani']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Villagómez']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Villapinzón']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Villeta']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Viotá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Yacopí']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Zipacón']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Zipaquirá']);
      DB::table('cities')->insert(['state' =>  14, 'name' => 'Útica']);
      DB::table('cities')->insert(['state' =>  15, 'name' => 'Inírida']);
      DB::table('cities')->insert(['state' =>  16, 'name' => 'Calamar']);
      DB::table('cities')->insert(['state' =>  16, 'name' => 'El Retorno']);
      DB::table('cities')->insert(['state' =>  16, 'name' => 'Miraflores']);
      DB::table('cities')->insert(['state' =>  16, 'name' => 'San José del Guaviare']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Acevedo']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Agrado']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Aipe']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Algeciras']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Altamira']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Baraya']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Campoalegre']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Colombia']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Elías']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Garzón']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Gigante']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Guadalupe']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Hobo']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Isnos']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'La Argentina']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'La Plata']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Neiva']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Nátaga']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Oporapa']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Paicol']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Palermo']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Palestina']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Pital']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Pitalito']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Rivera']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Saladoblanco']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'San Agustín']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Santa María']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Suaza']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Tarqui']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Tello']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Teruel']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Tesalia']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Timaná']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Villavieja']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Yaguará']);
      DB::table('cities')->insert(['state' =>  17, 'name' => 'Íquira']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Albania']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Barrancas']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Dibulla']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Distracción']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'El Molino']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Fonseca']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Hatonuevo']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'La Jagua del Pilar']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Maicao']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Manaure']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Riohacha']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'San Juan del Cesar']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Uribia']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Urumita']);
      DB::table('cities')->insert(['state' =>  18, 'name' => 'Villanueva']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Algarrobo']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Aracataca']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Ariguaní (El Difícil)']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Cerro San Antonio']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Chivolo']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Ciénaga']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Concordia']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'El Banco']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'El Piñon']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'El Retén']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Fundación']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Guamal']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Nueva Granada']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Pedraza']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Pijiño']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Pivijay']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Plato']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Puebloviejo']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Remolino']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Sabanas de San Angel (SAN ANGEL)']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Salamina']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'San Sebastián de Buenavista']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'San Zenón']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Santa Ana']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Santa Bárbara de Pinto']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Santa Marta']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Sitionuevo']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Tenerife']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Zapayán (PUNTA DE PIEDRAS)']);
      DB::table('cities')->insert(['state' =>  19, 'name' => 'Zona Bananera (PRADO - SEVILLA)']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Acacías']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Barranca de Upía']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Cabuyaro']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Castilla la Nueva']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Cubarral']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Cumaral']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'El Calvario']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'El Castillo']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'El Dorado']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Fuente de Oro']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Granada']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Guamal']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'La Macarena']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Lejanías']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Mapiripan']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Mesetas']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Puerto Concordia']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Puerto Gaitán']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Puerto Lleras']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Puerto López']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Puerto Rico']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Restrepo']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'San Carlos de Guaroa']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'San Juan de Arama']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'San Juanito']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'San Martín']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Uribe']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Villavicencio']);
      DB::table('cities')->insert(['state' =>  20, 'name' => 'Vista Hermosa']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Albán (San José)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Aldana']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Ancuya']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Arboleda (Berruecos)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Barbacoas']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Belén']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Buesaco']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Chachaguí']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Colón (Génova)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Consaca']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Contadero']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Cuaspud (Carlosama)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Cumbal']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Cumbitara']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Córdoba']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'El Charco']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'El Peñol']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'El Rosario']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'El Tablón de Gómez']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'El Tambo']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Francisco Pizarro']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Funes']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Guachavés']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Guachucal']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Guaitarilla']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Gualmatán']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Iles']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Imúes']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Ipiales']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'La Cruz']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'La Florida']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'La Llanada']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'La Tola']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'La Unión']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Leiva']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Linares']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Magüi (Payán)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Mallama (Piedrancha)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Mosquera']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Nariño']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Olaya Herrera']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Ospina']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Policarpa']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Potosí']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Providencia']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Puerres']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Pupiales']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Ricaurte']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Roberto Payán (San José)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Samaniego']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'San Bernardo']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'San Juan de Pasto']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'San Lorenzo']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'San Pablo']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'San Pedro de Cartago']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Sandoná']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Santa Bárbara (Iscuandé)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Sapuyes']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Sotomayor (Los Andes)']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Taminango']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Tangua']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Tumaco']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Túquerres']);
      DB::table('cities')->insert(['state' =>  21, 'name' => 'Yacuanquer']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Arboledas']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Bochalema']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Bucarasica']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Chinácota']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Chitagá']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Convención']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Cucutilla']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Cáchira']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Cácota']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Cúcuta']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Durania']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'El Carmen']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'El Tarra']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'El Zulia']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Gramalote']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Hacarí']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Herrán']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'La Esperanza']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'La Playa']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Labateca']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Los Patios']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Lourdes']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Mutiscua']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Ocaña']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Pamplona']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Pamplonita']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Puerto Santander']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Ragonvalia']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Salazar']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'San Calixto']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'San Cayetano']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Santiago']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Sardinata']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Silos']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Teorama']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Tibú']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Toledo']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Villa Caro']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Villa del Rosario']);
      DB::table('cities')->insert(['state' =>  22, 'name' => 'Ábrego']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Colón']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Mocoa']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Orito']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Puerto Asís']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Puerto Caicedo']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Puerto Guzmán']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Puerto Leguízamo']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'San Francisco']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'San Miguel']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Santiago']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Sibundoy']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Valle del Guamuez']);
      DB::table('cities')->insert(['state' =>  23, 'name' => 'Villagarzón']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Armenia']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Buenavista']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Calarcá']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Circasia']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Cordobá']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Filandia']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Génova']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'La Tebaida']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Montenegro']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Pijao']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Quimbaya']);
      DB::table('cities')->insert(['state' =>  24, 'name' => 'Salento']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Apía']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Balboa']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Belén de Umbría']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Dos Quebradas']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Guática']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'La Celia']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'La Virginia']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Marsella']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Mistrató']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Pereira']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Pueblo Rico']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Quinchía']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Santa Rosa de Cabal']);
      DB::table('cities')->insert(['state' =>  25, 'name' => 'Santuario']);
      DB::table('cities')->insert(['state' =>  26, 'name' => 'Providencia']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Aguada']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Albania']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Aratoca']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Barbosa']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Barichara']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Barrancabermeja']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Betulia']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Bolívar']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Bucaramanga']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Cabrera']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'California']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Capitanejo']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Carcasí']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Cepita']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Cerrito']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Charalá']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Charta']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Chima']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Chipatá']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Cimitarra']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Concepción']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Confines']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Contratación']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Coromoro']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Curití']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'El Carmen']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'El Guacamayo']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'El Peñon']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'El Playón']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Encino']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Enciso']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Floridablanca']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Florián']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Galán']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Girón']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Guaca']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Guadalupe']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Guapota']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Guavatá']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Guepsa']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Gámbita']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Hato']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Jesús María']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Jordán']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'La Belleza']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'La Paz']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Landázuri']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Lebrija']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Los Santos']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Macaravita']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Matanza']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Mogotes']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Molagavita']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Málaga']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Ocamonte']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Oiba']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Onzaga']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Palmar']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Palmas del Socorro']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Pie de Cuesta']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Pinchote']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Puente Nacional']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Puerto Parra']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Puerto Wilches']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Páramo']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Rio Negro']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Sabana de Torres']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Andrés']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Benito']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Gíl']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Joaquín']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San José de Miranda']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Miguel']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'San Vicente del Chucurí']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Santa Bárbara']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Santa Helena del Opón']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Simacota']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Socorro']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Suaita']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Sucre']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Suratá']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Tona']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Valle de San José']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Vetas']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Villanueva']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Vélez']);
      DB::table('cities')->insert(['state' =>  27, 'name' => 'Zapatoca']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Buenavista']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Caimito']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Chalán']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Colosó (Ricaurte)']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Corozal']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Coveñas']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'El Roble']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Galeras (Nueva Granada)']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Guaranda']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'La Unión']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Los Palmitos']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Majagual']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Morroa']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Ovejas']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Palmito']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Sampués']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'San Benito Abad']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'San Juan de Betulia']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'San Marcos']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'San Onofre']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'San Pedro']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Sincelejo']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Sincé']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Sucre']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Tolú']);
      DB::table('cities')->insert(['state' =>  28, 'name' => 'Tolú Viejo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Alpujarra']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Alvarado']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Ambalema']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Anzoátegui']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Armero (Guayabal)']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Ataco']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Cajamarca']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Carmen de Apicalá']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Casabianca']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Chaparral']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Coello']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Coyaima']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Cunday']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Dolores']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Espinal']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Falan']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Flandes']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Fresno']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Guamo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Herveo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Honda']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Ibagué']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Icononzo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Lérida']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Líbano']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Mariquita']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Melgar']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Murillo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Natagaima']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Ortega']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Palocabildo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Piedras']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Planadas']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Prado']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Purificación']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Rioblanco']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Roncesvalles']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Rovira']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Saldaña']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'San Antonio']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'San Luis']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Santa Isabel']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Suárez']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Valle de San Juan']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Venadillo']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Villahermosa']);
      DB::table('cities')->insert(['state' =>  29, 'name' => 'Villarrica']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Alcalá']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Andalucía']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Ansermanuevo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Argelia']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Bolívar']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Buenaventura']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Buga']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Bugalagrande']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Caicedonia']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Calima (Darién)']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Calí']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Candelaria']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Cartago']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Dagua']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'El Cairo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'El Cerrito']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'El Dovio']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'El Águila']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Florida']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Ginebra']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Guacarí']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Jamundí']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'La Cumbre']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'La Unión']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'La Victoria']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Obando']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Palmira']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Pradera']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Restrepo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Riofrío']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Roldanillo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'San Pedro']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Sevilla']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Toro']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Trujillo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Tulúa']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Ulloa']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Versalles']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Vijes']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Yotoco']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Yumbo']);
      DB::table('cities')->insert(['state' =>  30, 'name' => 'Zarzal']);
      DB::table('cities')->insert(['state' =>  31, 'name' => 'Carurú']);
      DB::table('cities')->insert(['state' =>  31, 'name' => 'Mitú']);
      DB::table('cities')->insert(['state' =>  31, 'name' => 'Taraira']);
      DB::table('cities')->insert(['state' =>  32, 'name' => 'Cumaribo']);
      DB::table('cities')->insert(['state' =>  32, 'name' => 'La Primavera']);
      DB::table('cities')->insert(['state' =>  32, 'name' => 'Puerto Carreño']);
      DB::table('cities')->insert(['state' =>  32, 'name' => 'Santa Rosalía']);
    }
}
